name: Deploy to Cloud Run

env:
  SERVICE_NAME: github-action-gcpapi
  PROJECT_ID: ideeyn-api
  DOCKER_IMAGE_URL: asia-southeast2-docker.pkg.dev/ideeyn-api/github-action-gcpapi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCPAPI_CLOUDRUN_KEY }}"
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name:
          Configure Docker
          # gcloud auth login --no-launch-browser
          # 4/0AanRRrt_dKyGfigPIWAngmQoNnvX0ALAMs82gOeIWDIr8BIb4eMlIcdBYrQe3ugx-grAZQ
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          gcloud auth print-access-token
          docker login -u oauth2accesstoken --password-stdin https://asia-southeast2-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME: SERVICE_NAME
          gcloud run deploy SERVICE_NAME \
          --image ${{ env.DOCKER_IMAGE_URL }}:latest \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated
